# Generated by Django 3.1.3 on 2020-11-25 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0002_auto_20201125_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appeal',
            name='due',
        ),
    ]
