# Generated by Django 3.1.3 on 2020-11-27 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0003_remove_appeal_due'),
    ]

    operations = [
        migrations.CreateModel(
            name='tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='appeal',
            name='description',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=70)),
                ('description', models.TextField()),
                ('amount', models.IntegerField(default='1')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(to='appeals.tags')),
            ],
        ),
        migrations.AddField(
            model_name='appeal',
            name='tags',
            field=models.ManyToManyField(to='appeals.tags'),
        ),
    ]
